---
collections:
  - name: community.general
    version: 11.2.1
  - name: community.proxmox
    version: 1.3.0
  - name: community.sops
    version: 2.2.4
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: kubernetes.core
    version: 6.1.0
  - name: artis3n.tailscale
    version: 1.0.1
  - name: prometheus.prometheus
    version: 0.27.5
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.5.0
